 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild NetSoftwareUpdateChecker/NetSoftwareUpdateChecker.csproj /t:restore
       - run: msbuild NetSoftwareUpdateChecker/NetSoftwareUpdateChecker.csproj /p:Configuration=Release
       - run: 
          name: Push to NuGet
          command: |
            NetSoftwareUpdateChecker/NuGet-Push.ps1
            